version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight dashboard
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    restart: unless-stopped

  app:
    image: node:latest
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: sh -c "npm install -g && sleep 5 && npm run seed && npm run dev"
    depends_on:
      - redis
    stdin_open: true
    tty: true
